name: Build Patches
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Checkout build dependencies
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: dependencies
        repository: Sharkkit/Dependencies
        token: ${{ secrets.PAT_DEPENDENCIES }}
        
    - name: Checkout API
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: api
        repository: Sharkkit/API
      
    - name: Checkout Dedicated
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: dedicated
        repository: Sharkkit/Dedicated
        
    - name: Checkout Papier
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: papier
        repository: MeFisto94/Papier
        
    - name: Copy dependencies to dedicated
      # Powershell syntax!
      run: Copy-Item 'dependencies' -Destination 'dedicated/Dependencies' -Recurse

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
       
    #- name: Setup NuGet
    #  uses: NuGet/setup-nuget@v1.0.2
     
    #- name: Restore NuGet Packages
    #  run: nuget restore SharkkitDedicated.csproj
 
    - name: Build API
      run: msbuild SharkkitAPI.csproj /p:Configuration=Release
      working-directory: api
      
    - name: Build Dedicated
      run: msbuild SharkkitDedicated.csproj /p:Configuration=Release
      working-directory: dedicated
      
    - name: Setup Papier Workspace # Requires Powershell 7
      run: |
        New-Item -Path 'work' -ItemType Directory &&
        New-Item -Path 'work\BuildData' -ItemType Directory &&
        Copy-Item 'dependencies\Game\*' -Destination 'work\BuildData' -Recurse &&
        Copy-Item 'dependencies\Runtime\*' -Destination 'work\BuildData' -Recurse &&
        Copy-Item 'dependencies\UnityEngine\*' -Destination 'work\BuildData' -Recurse
      
    - name: Apply the Patches
      run: dotnet run --project papier/Papier.csproj -- applyPatches
